version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running tests..."
      - npm run test
  build:
    commands:
      - echo "Building the application..."
      - npm run build # Replace 'build' with your build script if defined in package.json

artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*' # Exclude node_modules to reduce artifact size
  discard-paths: no
