version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running tests..."
      - npm test # Runs the test script defined in your package.json
  build:
    commands:
      - echo "Preparing production build..."
      - npm run build || echo "No build script defined, skipping build step."
artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*' # Exclude node_modules to save storage space
  discard-paths: no
