version: 2.1
orbs:
  docker: circleci/docker@1.1.0
jobs:
  build_and_push:
    docker:
      - image: circleci/python:3.8
    working_directory: /home/circleci/project
    steps:
      - checkout
      # Use the docker orb to build and push the Docker image
      - docker/build:
          context: .
          dockerfile: Dockerfile
          image: username/notes:${CIRCLE_SHA1}
          registry-url: docker.io
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
          tag: ${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push
