version: 2.1
orbs:
  docker: circleci/docker@1.1.0
parameters:
  build_job:
    type: string
    default: ''

jobs:
  build_and_push_job1:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Log in to Docker Hub
          command: docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_ACCESS_TOKEN}"
      - conditional:
          steps:
            - when: \<< pipeline.parameters.build_job == 'job1' >>
              continue-on-error: true
              run:
                name: Build and push Docker image
                command: |
                 if [ "${CIRCLE_JOB}" == "build_and_push_job1" ]; then
                  docker build -t "${DOCKER_HUB_USERNAME}/notes:${CIRCLE_SHA1}" -t "${DOCKER_HUB_USERNAME}/notes:latest" .
                  docker push "${DOCKER_HUB_USERNAME}/notes:${CIRCLE_SHA1}" 
                  docker push "${DOCKER_HUB_USERNAME}/notes:latest"
                 fi 
workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push_job1:
         
