version: 2.1
orbs:
  docker: circleci/docker@1.1.0
jobs:
  build_and_push:
    docker:
      - image: circleci/python:3.8
    working_directory: /home/circleci/project
    steps:
      - checkout
          # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: docker login -u "${DOCKER_HUB_USERNAME}" -p  "${DOCKER_HUB_ACCESS_TOKEN}"
    


      # Build the Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t "${DOCKER_HUB_USERNAME}"/notes:latest .
      
      # Push the Docker image to Docker Hubb
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push "${DOCKER_HUB_USERNAME}"/notes:latest

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push
