version: 2.1
orbs:
  docker: circleci/docker@1.1.0

jobs:
  build_and_push:
    docker:
      - image: circleci/python:3.8  # Choose an image that supports Docker (e.g., Python or Docker itself).
        environment:
          DOCKER_HOST: tcp://localhost:2375  # Enable Docker-in-Docker (DinD) for building Docker images within the job.
    working_directory:  /home/circleci/project

    steps:
      - checkout

      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: docker login -u haroonniamat029 -p "demon392087" 


      # Build the Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t haroonniamat029/notes:latest .
      
      # Push the Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push haroonniamat029/notes:latest
workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push
