version: 2.1
orbs:
  docker: circleci/docker@1.1.0
parameters:
  trigger:
    type: boolean
    default: false

jobs:
  job1:
    docker:
      - image: circleci/python:3.8
    working_directory: /home/circleci/project
    steps:
      - checkout
      # Set up Docker-in-Docker environment
      - setup_remote_docker:
          version: 20.10.7  # Use the desired version of Docker
      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_ACCESS_TOKEN}"

      # Build the Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t "${DOCKER_HUB_USERNAME}/notes:${CIRCLE_SHA1}" -t "${DOCKER_HUB_USERNAME}/notes:latest" .
      
      # Push the Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push "${DOCKER_HUB_USERNAME}/notes:${CIRCLE_SHA1}" 
            docker push "${DOCKER_HUB_USERNAME}/notes:latest"

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push:
          when: << pipeline.parameters.trigger >>
