apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    nginx.org/client-max-body-size: "1G"

  name: todo-app
  namespace: notes
spec:
  rules:
  - host: myapp.devclouds.live
    http:
      paths:
      - backend:
          service:
            name: todo-app
            port:
              number: 8000
      
